trigger:
  none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    values:
      - dev
      - qa
      - prod

variables:
  - template: vars/vars-{{ parameters.environment }}.yml

stages:
- template: templates/stages/stage-lint.yml

- template: templates/stages/stage-validate.yml

- template: templates/stages/stage-preview.yml

- template: templates/stages/stage-deploy.yml